galerie_index:
    path:     /
    defaults: { _controller: "IschaBackOfficeBundle:Galerie:index" }
    methods:  GET

galerie_show:
    path:     /{id}/show
    defaults: { _controller: "IschaBackOfficeBundle:Galerie:show" }
    methods:  GET

galerie_new:
    path:     /new
    defaults: { _controller: "IschaBackOfficeBundle:Galerie:new" }
    methods:  [GET, POST]

galerie_edit:
    path:     /{id}/edit
    defaults: { _controller: "IschaBackOfficeBundle:Galerie:edit" }
    methods:  [GET, POST]

galerie_delete:
    path:     /{id}/delete
    defaults: { _controller: "IschaBackOfficeBundle:Galerie:delete" }
    methods:  DELETE
