lieu_index:
    path:     /
    defaults: { _controller: "IschaBackOfficeBundle:Lieu:index" }
    methods:  GET

lieu_show:
    path:     /{id}/show
    defaults: { _controller: "IschaBackOfficeBundle:Lieu:show" }
    methods:  GET

lieu_new:
    path:     /new
    defaults: { _controller: "IschaBackOfficeBundle:Lieu:new" }
    methods:  [GET, POST]

lieu_edit:
    path:     /{id}/edit
    defaults: { _controller: "IschaBackOfficeBundle:Lieu:edit" }
    methods:  [GET, POST]

lieu_delete:
    path:     /{id}/delete
    defaults: { _controller: "IschaBackOfficeBundle:Lieu:delete" }
    methods:  DELETE
