rendezvous_index:
    path:     /
    defaults: { _controller: "IschaBackOfficeBundle:RendezVous:index" }
    methods:  GET

rendezvous_show:
    path:     /{id}/show
    defaults: { _controller: "IschaBackOfficeBundle:RendezVous:show" }
    methods:  GET

rendezvous_new:
    path:     /new
    defaults: { _controller: "IschaBackOfficeBundle:RendezVous:new" }
    methods:  [GET, POST]

rendezvous_edit:
    path:     /{id}/edit
    defaults: { _controller: "IschaBackOfficeBundle:RendezVous:edit" }
    methods:  [GET, POST]

rendezvous_delete:
    path:     /{id}/delete
    defaults: { _controller: "IschaBackOfficeBundle:RendezVous:delete" }
    methods:  DELETE
