tarif_index:
    path:     /
    defaults: { _controller: "IschaBackOfficeBundle:Tarif:index" }
    methods:  GET

tarif_show:
    path:     /{id}/show
    defaults: { _controller: "IschaBackOfficeBundle:Tarif:show" }
    methods:  GET

tarif_new:
    path:     /new
    defaults: { _controller: "IschaBackOfficeBundle:Tarif:new" }
    methods:  [GET, POST]

tarif_edit:
    path:     /{id}/edit
    defaults: { _controller: "IschaBackOfficeBundle:Tarif:edit" }
    methods:  [GET, POST]

tarif_delete:
    path:     /{id}/delete
    defaults: { _controller: "IschaBackOfficeBundle:Tarif:delete" }
    methods:  DELETE
