<?php

namespace Ischa\BackOfficeBundle\Repository;

/**
 * CoiffureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoiffureRepository extends \Doctrine\ORM\EntityRepository
{
}
