<?php

namespace Ischa\BackOfficeBundle\Repository;

/**
 * RendezVousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezVousRepository extends \Doctrine\ORM\EntityRepository
{
}
